[project]
name = "edl-src"
version = "0.1.0"
description = ""
authors = [
    {name = "\"omarmeks89\""}
]
license = {text = "GPL3.0"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "annotated-types (==0.7.0)",
    "assertpy (==1.1)",
    "black (==25.1.0)",
    "click (==8.1.8)",
    "iniconfig (==2.1.0)",
    "mypy-extensions (==1.0.0)",
    "packaging (==24.2)",
    "pathspec (==0.12.1)",
    "platformdirs (==4.3.7)",
    "pluggy (==1.5.0)",
    "pydantic (==2.11.4)",
    "pydantic-core (==2.33.2)",
    "pytest (==8.3.5)",
    "pyyaml (==6.0.2)",
    "typing-inspection (==0.4.0)",
    "typing-extensions (==4.13.2)",
    "ruff (>=0.13.3,<0.14.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
